/*******************************************************************
This file has been automatically generated by ispc
DO NOT EDIT THIS FILE DIRECTLY
*******************************************************************/

extern "C" {
int puts(unsigned char *);
unsigned int putchar(unsigned int);
int fflush(void *);
int printf(const unsigned char *, ...);
uint8_t *memcpy(uint8_t *, uint8_t *, uint64_t);
uint8_t *memset(uint8_t *, uint8_t, uint64_t);
void memset_pattern16(void *, const void *, uint64_t);
}

typedef unsigned char bool;

typedef uint64_t ConstantDoubleTy;
typedef uint32_t ConstantFloatTy;
typedef struct {
  unsigned long long f1;
  unsigned short f2;
  unsigned short pad[3];
} ConstantFP80Ty;
typedef struct { uint64_t f1, f2; } ConstantFP128Ty;

typedef union {
  unsigned int Int32;
  unsigned long long Int64;
  float Float;
  double Double;
} llvmBitCastUnion;

/* This is special class, designed for operations with long int.*/
namespace {
template <int num_bits> struct iN {
  int num[num_bits / (sizeof(int) * 8)];

  iN() {}

  iN(const char *val) {
    if (val == NULL)
      return;
    int length = num_bits / (sizeof(int) * 8);
    int val_len = 0;
    for (val_len = 0; val[val_len]; (val_len)++)
      ;
    for (int i = 0; (i < val_len && i < num_bits); i++)
      num[i / (sizeof(int) * 8)] =
          (num[i / (sizeof(int) * 8)] << 1) | (val[i] - '0');
  }

  ~iN() {}

  iN operator>>(const iN rhs) {
    iN res;
    int length = num_bits / (sizeof(int) * 8);
    int cells_shift = rhs.num[0] / (sizeof(int) * 8);
    int small_shift = rhs.num[0] % (sizeof(int) * 8);
    for (int i = 0; i < (length - cells_shift); i++)
      res.num[i] = this->num[cells_shift + i];
    for (int i = 0; i < length - 1; i++) {
      res.num[i] = this->num[i] >> small_shift;
      res.num[i] = ((this->num[i + 1] << ((sizeof(int) * 8) - small_shift))) |
                   res.num[i];
    }
    res.num[length - 1] = res.num[length - 1] >> small_shift;
    return res;
  }

  iN operator&(iN rhs) {
    iN res;
    int length = num_bits / (sizeof(int) * 8);
    for (int i = 0; i < length; i++)
      res.num[i] = (this->num[i]) & (rhs.num[i]);
    return res;
  }

  operator uint32_t() { return this->num[0]; }

  template <class T> friend iN<num_bits> __cast_bits(iN<num_bits> to, T from) {
    for (int i = 0; i < 4; i++)
      to.num[i] = ((int *)(&from))[i];
    return to;
  }

  template <class T> friend T __cast_bits(T to, iN<num_bits> from) {
    for (int i = 0; i < 4; i++)
      ((int *)(&to))[i] = from.num[i];
    return to;
  }

  template <int ALIGN, class T> friend void __store(T *p, iN<num_bits> val) {
    for (int i = 0; i < 4; i++)
      ((int *)p)[i] = val.num[i];
  }
};
};

namespace {
struct l_array_0;
};

namespace {
struct l_array_0 {
  static l_array_0 init(__vec4_f v0, __vec4_f v1, __vec4_f v2, __vec4_f v3) {
    l_array_0 ret;
    ret.array[0] = v0;
    ret.array[1] = v1;
    ret.array[2] = v2;
    ret.array[3] = v3;
    return ret;
  }
  __vec4_f array[4];
};
};

extern uint32_t programCount __ATTRIBUTE_WEAK__;
extern __vec4_i32 programIndex __ATTRIBUTE_WEAK__;
extern uint32_t __math_lib __ATTRIBUTE_WEAK__;
extern uint32_t __math_lib_ispc __ATTRIBUTE_WEAK__;
extern uint32_t __math_lib_ispc_fast __ATTRIBUTE_WEAK__;
extern uint32_t __math_lib_svml __ATTRIBUTE_WEAK__;
extern uint32_t __math_lib_system __ATTRIBUTE_WEAK__;
extern uint32_t __have_native_half __ATTRIBUTE_WEAK__;
extern uint32_t __have_native_rand __ATTRIBUTE_WEAK__;
extern uint32_t __have_native_transcendentals __ATTRIBUTE_WEAK__;
extern uint32_t __have_native_trigonometry __ATTRIBUTE_WEAK__;
extern uint32_t __have_native_rsqrtd __ATTRIBUTE_WEAK__;
extern uint32_t __have_native_rcpd __ATTRIBUTE_WEAK__;
extern uint32_t __is_nvptx_target __ATTRIBUTE_WEAK__;

extern "C" {
void hwc2cwh___uniuniun_3C_unf_3E_un_3C_unf_3E_un_3C_unf_3E_(
    uint32_t width_, uint32_t height_, float *mean_, float *input_,
    float *result_, __vec4_i1 __mask_);
void hwc2cwh2___uniuniun_3C_unf_3E_un_3C_unf_3E_(uint32_t width_,
                                                 uint32_t height_,
                                                 float *input_, float *result_,
                                                 __vec4_i1 __mask_);
void hwc2cwh(uint32_t width_, uint32_t height_, float *mean_, float *input_,
             float *result_);
void hwc2cwh2(uint32_t width_, uint32_t height_, float *input_, float *result_);
}

template <typename A, typename B> static inline int llvm_fcmp_ord(A X, B Y) {
  return X == X && Y == Y;
}
template <typename A, typename B> static inline int llvm_fcmp_uno(A X, B Y) {
  return X != X || Y != Y;
}
template <typename A, typename B> static inline int llvm_fcmp_ueq(A X, B Y) {
  return X == Y || llvm_fcmp_uno(X, Y);
}
template <typename A, typename B> static inline int llvm_fcmp_une(A X, B Y) {
  return X != Y;
}
template <typename A, typename B> static inline int llvm_fcmp_ult(A X, B Y) {
  return X < Y || llvm_fcmp_uno(X, Y);
}
template <typename A, typename B> static inline int llvm_fcmp_ugt(A X, B Y) {
  return X > Y || llvm_fcmp_uno(X, Y);
}
template <typename A, typename B> static inline int llvm_fcmp_ule(A X, B Y) {
  return X <= Y || llvm_fcmp_uno(X, Y);
}
template <typename A, typename B> static inline int llvm_fcmp_uge(A X, B Y) {
  return X >= Y || llvm_fcmp_uno(X, Y);
}
template <typename A, typename B> static inline int llvm_fcmp_oeq(A X, B Y) {
  return X == Y;
}
template <typename A, typename B> static inline int llvm_fcmp_one(A X, B Y) {
  return X != Y && llvm_fcmp_ord(X, Y);
}
template <typename A, typename B> static inline int llvm_fcmp_olt(A X, B Y) {
  return X < Y;
}
template <typename A, typename B> static inline int llvm_fcmp_ogt(A X, B Y) {
  return X > Y;
}
template <typename A, typename B> static inline int llvm_fcmp_ole(A X, B Y) {
  return X <= Y;
}
template <typename A, typename B> static inline int llvm_fcmp_oge(A X, B Y) {
  return X >= Y;
}
template <typename A> A *Memset(A *ptr, int count, size_t len) {
  return (A *)memset(ptr, count, len);
}

uint32_t programCount __ATTRIBUTE_WEAK__ = (4u);
__vec4_i32 programIndex __ATTRIBUTE_WEAK__ = (__vec4_i32(0u, 1u, 2u, 3u));
uint32_t __math_lib __ATTRIBUTE_WEAK__ = 0u;
uint32_t __math_lib_ispc __ATTRIBUTE_WEAK__ = 0u;
uint32_t __math_lib_ispc_fast __ATTRIBUTE_WEAK__ = (1u);
uint32_t __math_lib_svml __ATTRIBUTE_WEAK__ = (2u);
uint32_t __math_lib_system __ATTRIBUTE_WEAK__ = (3u);
uint32_t __have_native_half __ATTRIBUTE_WEAK__ = (1u);
uint32_t __have_native_rand __ATTRIBUTE_WEAK__ = 0u;
uint32_t __have_native_transcendentals __ATTRIBUTE_WEAK__ = (1u);
uint32_t __have_native_trigonometry __ATTRIBUTE_WEAK__ = (1u);
uint32_t __have_native_rsqrtd __ATTRIBUTE_WEAK__ = (1u);
uint32_t __have_native_rcpd __ATTRIBUTE_WEAK__ = (1u);
uint32_t __is_nvptx_target __ATTRIBUTE_WEAK__ = 0u;

void hwc2cwh___uniuniun_3C_unf_3E_un_3C_unf_3E_un_3C_unf_3E_(
    uint32_t width_, uint32_t height_, float *mean_, float *input_,
    float *result_, __vec4_i1 __mask_) {
  __vec4_f x1_2e_i_; /* Address-exposed local */
  __vec4_f y1_2e_i_; /* Address-exposed local */
  __vec4_f z1_2e_i_; /* Address-exposed local */
  __vec4_f x2_2e_i_; /* Address-exposed local */
  __vec4_f y2_2e_i_; /* Address-exposed local */
  __vec4_f z2_2e_i_; /* Address-exposed local */
  __vec4_f x3_2e_i_; /* Address-exposed local */
  __vec4_f y3_2e_i_; /* Address-exposed local */
  __vec4_f z3_2e_i_; /* Address-exposed local */
  __vec4_f x4_2e_i_; /* Address-exposed local */
  __vec4_f y4_2e_i_; /* Address-exposed local */
  __vec4_f z4_2e_i_; /* Address-exposed local */
  uint8_t *tmp__1_;
  uint8_t *tmp__2_;
  uint8_t *tmp__3_;
  uint8_t *tmp__4_;
  uint8_t *tmp__5_;
  uint8_t *tmp__6_;
  uint8_t *tmp__7_;
  uint8_t *tmp__8_;
  uint8_t *tmp__9_;
  uint8_t *tmp__10_;
  uint8_t *tmp__11_;
  uint8_t *tmp__12_;
  uint32_t bitop_2e_i_;
  uint32_t mul_width_load72_height_load73_2e_i_;
  uint32_t mul__mul_width_load93_height_load94_2e_i_;
  uint32_t j_load102_plus1_2e_i_2e_us_;
  uint32_t i_2e_0_2e_i9_2e_us_;
  uint32_t i_2e_0_2e_i9_2e_us___PHI;
  uint32_t add_offset_load_i_load19_2e_i_2e_us_;
  uint64_t add_add_offset_load_i_load19__to_int64_2e_i_2e_us_;
  __vec4_f x1_load_2e_i_2e_us_;
  __vec4_f x2_load_2e_i_2e_us_;
  __vec4_f x3_load_2e_i_2e_us_;
  __vec4_f x4_load_2e_i_2e_us_;
  __vec4_f y1_load78_2e_i_2e_us_;
  __vec4_f y2_load79_2e_i_2e_us_;
  __vec4_f y3_load80_2e_i_2e_us_;
  __vec4_f y4_load81_2e_i_2e_us_;
  __vec4_f z1_load89_2e_i_2e_us_;
  __vec4_f z2_load90_2e_i_2e_us_;
  __vec4_f z3_load91_2e_i_2e_us_;
  __vec4_f z4_load92_2e_i_2e_us_;
  uint32_t add_i_load101_stride_load_2e_i_2e_us_;
  uint32_t j_2e_0_2e_i11_2e_us_;
  uint32_t j_2e_0_2e_i11_2e_us___PHI;
  uint32_t mul_j_load9_height_load10_2e_i_2e_us_;
  float mean_load_offset_load_2e_i_2e_us_;
  __vec4_f mean_load_offset_load_2e_i_2e_us_smear_;
  uint32_t add_mul__mul_width_load82_height_load83_offset_load84_2e_i_2e_us_;
  uint32_t add_mul__mul_width_load93_height_load94_offset_load95_2e_i_2e_us_;

  ;
  ;
  ;
  ;
  ;
  ;
  tmp__1_ = ((uint8_t *)(&x1_2e_i_));
  tmp__2_ = ((uint8_t *)(&y1_2e_i_));
  tmp__3_ = ((uint8_t *)(&z1_2e_i_));
  tmp__4_ = ((uint8_t *)(&x2_2e_i_));
  tmp__5_ = ((uint8_t *)(&y2_2e_i_));
  tmp__6_ = ((uint8_t *)(&z2_2e_i_));
  tmp__7_ = ((uint8_t *)(&x3_2e_i_));
  tmp__8_ = ((uint8_t *)(&y3_2e_i_));
  tmp__9_ = ((uint8_t *)(&z3_2e_i_));
  tmp__10_ = ((uint8_t *)(&x4_2e_i_));
  tmp__11_ = ((uint8_t *)(&y4_2e_i_));
  tmp__12_ = ((uint8_t *)(&z4_2e_i_));
  ;
  bitop_2e_i_ = width_ & 4294967292u;
  ;
  ;
  if ((((int32_t)height_) > ((int32_t)0u))) {
    goto for_loop_2e_i_2e_lr_2e_ph_label;
  } else {
    goto hwc2cwh____uniuniun_3C_unf_3E_un_3C_unf_3E_un_3C_unf_3E__2e_exit_label;
  }

for_loop_2e_i_2e_lr_2e_ph_label : {
  mul_width_load72_height_load73_2e_i_ =
      ((uint32_t)(((uint32_t)height_) * ((uint32_t)width_)));
  mul__mul_width_load93_height_load94_2e_i_ =
      mul_width_load72_height_load73_2e_i_ << 1u;
  if ((((int32_t)width_) > ((int32_t)0u))) {
    j_2e_0_2e_i11_2e_us___PHI = 0u; /* for PHI node */
    goto for_loop13_2e_i_2e_lr_2e_ph_2e_us_label;
  } else {
    goto hwc2cwh____uniuniun_3C_unf_3E_un_3C_unf_3E_un_3C_unf_3E__2e_exit_label;
  }
}
  do { /* Syntactic loop 'for_loop13.i.lr.ph.us' to make GCC happy */
  for_loop13_2e_i_2e_lr_2e_ph_2e_us_label : {
    j_2e_0_2e_i11_2e_us_ = j_2e_0_2e_i11_2e_us___PHI;
    mul_j_load9_height_load10_2e_i_2e_us_ =
        ((uint32_t)(((uint32_t)j_2e_0_2e_i11_2e_us_) * ((uint32_t)height_)));
    ;
    ;
    mean_load_offset_load_2e_i_2e_us_ = *mean_;
    mean_load_offset_load_2e_i_2e_us_smear_ =
        __smear_float<__vec4_f>(mean_load_offset_load_2e_i_2e_us_);
    add_mul__mul_width_load82_height_load83_offset_load84_2e_i_2e_us_ =
        ((uint32_t)(((uint32_t)mul_j_load9_height_load10_2e_i_2e_us_) +
                    ((uint32_t)mul_width_load72_height_load73_2e_i_)));
    add_mul__mul_width_load93_height_load94_offset_load95_2e_i_2e_us_ =
        ((uint32_t)(((uint32_t)mul_j_load9_height_load10_2e_i_2e_us_) +
                    ((uint32_t)mul__mul_width_load93_height_load94_2e_i_)));
    i_2e_0_2e_i9_2e_us___PHI = 0u; /* for PHI node */
    goto for_loop13_2e_i_2e_us_label;
  }
    do { /* Syntactic loop 'for_loop13.i.us' to make GCC happy */
    for_loop13_2e_i_2e_us_label : {
      i_2e_0_2e_i9_2e_us_ = i_2e_0_2e_i9_2e_us___PHI;
      add_offset_load_i_load19_2e_i_2e_us_ =
          ((uint32_t)(((uint32_t)i_2e_0_2e_i9_2e_us_) +
                      ((uint32_t)mul_j_load9_height_load10_2e_i_2e_us_)));
      add_add_offset_load_i_load19__to_int64_2e_i_2e_us_ =
          ((int64_t)(int32_t)add_offset_load_i_load19_2e_i_2e_us_);
      ;
      ;
      ;
      ;
      __aos_to_soa3_float(
          ((&input_[(
              (int64_t)add_add_offset_load_i_load19__to_int64_2e_i_2e_us_)])),
          (&x1_2e_i_), (&y1_2e_i_), (&z1_2e_i_));
      ;
      ;
      ;
      ;
      __aos_to_soa3_float(((&input_[((int64_t)(((int64_t)(int32_t)(((uint32_t)(
                              ((uint32_t)add_offset_load_i_load19_2e_i_2e_us_) +
                              ((uint32_t)1u)))))))])),
                          (&x2_2e_i_), (&y2_2e_i_), (&z2_2e_i_));
      ;
      ;
      ;
      ;
      __aos_to_soa3_float(((&input_[((int64_t)(((int64_t)(int32_t)(((uint32_t)(
                              ((uint32_t)add_offset_load_i_load19_2e_i_2e_us_) +
                              ((uint32_t)2u)))))))])),
                          (&x3_2e_i_), (&y3_2e_i_), (&z3_2e_i_));
      ;
      ;
      ;
      ;
      __aos_to_soa3_float(((&input_[((int64_t)(((int64_t)(int32_t)(((uint32_t)(
                              ((uint32_t)add_offset_load_i_load19_2e_i_2e_us_) +
                              ((uint32_t)3u)))))))])),
                          (&x4_2e_i_), (&y4_2e_i_), (&z4_2e_i_));
      ;
      x1_load_2e_i_2e_us_ = __load<16>((&x1_2e_i_));
      ;
      ;
      x2_load_2e_i_2e_us_ = __load<16>((&x2_2e_i_));
      ;
      ;
      x3_load_2e_i_2e_us_ = __load<16>((&x3_2e_i_));
      ;
      ;
      x4_load_2e_i_2e_us_ = __load<16>((&x4_2e_i_));
      ;
      ;
      ;
      ;
      ;
      ;
      ;
      ;
      ;
      __soa_to_aos4_float(
          (__sub(x1_load_2e_i_2e_us_, mean_load_offset_load_2e_i_2e_us_smear_)),
          (__sub(x2_load_2e_i_2e_us_, mean_load_offset_load_2e_i_2e_us_smear_)),
          (__sub(x3_load_2e_i_2e_us_, mean_load_offset_load_2e_i_2e_us_smear_)),
          (__sub(x4_load_2e_i_2e_us_, mean_load_offset_load_2e_i_2e_us_smear_)),
          ((&result_[(
              (int64_t)add_add_offset_load_i_load19__to_int64_2e_i_2e_us_)])));
      y1_load78_2e_i_2e_us_ = __load<16>((&y1_2e_i_));
      ;
      y2_load79_2e_i_2e_us_ = __load<16>((&y2_2e_i_));
      ;
      y3_load80_2e_i_2e_us_ = __load<16>((&y3_2e_i_));
      ;
      y4_load81_2e_i_2e_us_ = __load<16>((&y4_2e_i_));
      ;
      ;
      __soa_to_aos4_float(
          y1_load78_2e_i_2e_us_, y2_load79_2e_i_2e_us_, y3_load80_2e_i_2e_us_,
          y4_load81_2e_i_2e_us_,
          ((&result_[((int64_t)(((int64_t)(int32_t)(((uint32_t)(
              ((uint32_t)
                   add_mul__mul_width_load82_height_load83_offset_load84_2e_i_2e_us_) +
              ((uint32_t)i_2e_0_2e_i9_2e_us_)))))))])));
      z1_load89_2e_i_2e_us_ = __load<16>((&z1_2e_i_));
      ;
      z2_load90_2e_i_2e_us_ = __load<16>((&z2_2e_i_));
      ;
      z3_load91_2e_i_2e_us_ = __load<16>((&z3_2e_i_));
      ;
      z4_load92_2e_i_2e_us_ = __load<16>((&z4_2e_i_));
      ;
      ;
      __soa_to_aos4_float(
          z1_load89_2e_i_2e_us_, z2_load90_2e_i_2e_us_, z3_load91_2e_i_2e_us_,
          z4_load92_2e_i_2e_us_,
          ((&result_[((int64_t)(((int64_t)(int32_t)(((uint32_t)(
              ((uint32_t)
                   add_mul__mul_width_load93_height_load94_offset_load95_2e_i_2e_us_) +
              ((uint32_t)i_2e_0_2e_i9_2e_us_)))))))])));
      add_i_load101_stride_load_2e_i_2e_us_ = ((uint32_t)(
          ((uint32_t)i_2e_0_2e_i9_2e_us_) + ((uint32_t)bitop_2e_i_)));
      ;
      if ((((int32_t)add_i_load101_stride_load_2e_i_2e_us_) <
           ((int32_t)width_))) {
        i_2e_0_2e_i9_2e_us___PHI =
            add_i_load101_stride_load_2e_i_2e_us_; /* for PHI node */
        goto for_loop13_2e_i_2e_us_label;
      } else {
        goto for_exit14_2e_i_2e_us_label;
      }
    }
    } while (1); /* end of syntactic loop 'for_loop13.i.us' */
  for_exit14_2e_i_2e_us_label : {
    j_load102_plus1_2e_i_2e_us_ =
        ((uint32_t)(((uint32_t)j_2e_0_2e_i11_2e_us_) + ((uint32_t)1u)));
    ;
    if ((j_load102_plus1_2e_i_2e_us_ == height_)) {
      goto hwc2cwh____uniuniun_3C_unf_3E_un_3C_unf_3E_un_3C_unf_3E__2e_exit_label;
    } else {
      j_2e_0_2e_i11_2e_us___PHI =
          j_load102_plus1_2e_i_2e_us_; /* for PHI node */
      goto for_loop13_2e_i_2e_lr_2e_ph_2e_us_label;
    }
  }
  } while (1); /* end of syntactic loop 'for_loop13.i.lr.ph.us' */
hwc2cwh____uniuniun_3C_unf_3E_un_3C_unf_3E_un_3C_unf_3E__2e_exit_label : {
  return;
}
}

void hwc2cwh2___uniuniun_3C_unf_3E_un_3C_unf_3E_(uint32_t width_,
                                                 uint32_t height_,
                                                 float *input_, float *result_,
                                                 __vec4_i1 __mask_) {
  __vec4_f x1_2e_i_; /* Address-exposed local */
  __vec4_f y1_2e_i_; /* Address-exposed local */
  __vec4_f z1_2e_i_; /* Address-exposed local */
  __vec4_f x2_2e_i_; /* Address-exposed local */
  __vec4_f y2_2e_i_; /* Address-exposed local */
  __vec4_f z2_2e_i_; /* Address-exposed local */
  __vec4_f x3_2e_i_; /* Address-exposed local */
  __vec4_f y3_2e_i_; /* Address-exposed local */
  __vec4_f z3_2e_i_; /* Address-exposed local */
  __vec4_f x4_2e_i_; /* Address-exposed local */
  __vec4_f y4_2e_i_; /* Address-exposed local */
  __vec4_f z4_2e_i_; /* Address-exposed local */
  uint8_t *tmp__13_;
  uint8_t *tmp__14_;
  uint8_t *tmp__15_;
  uint8_t *tmp__16_;
  uint8_t *tmp__17_;
  uint8_t *tmp__18_;
  uint8_t *tmp__19_;
  uint8_t *tmp__20_;
  uint8_t *tmp__21_;
  uint8_t *tmp__22_;
  uint8_t *tmp__23_;
  uint8_t *tmp__24_;
  uint32_t bitop_2e_i_;
  uint32_t mul_width_load72_height_load73_2e_i_;
  uint32_t mul__mul_width_load93_height_load94_2e_i_;
  uint32_t j_load102_plus1_2e_i_2e_us_;
  uint32_t i_2e_0_2e_i8_2e_us_;
  uint32_t i_2e_0_2e_i8_2e_us___PHI;
  uint32_t add_offset_load_i_load19_2e_i_2e_us_;
  uint64_t add_add_offset_load_i_load19__to_int64_2e_i_2e_us_;
  __vec4_f x1_load_2e_i_2e_us_;
  __vec4_f x2_load_2e_i_2e_us_;
  __vec4_f x3_load_2e_i_2e_us_;
  __vec4_f x4_load_2e_i_2e_us_;
  __vec4_f y1_load78_2e_i_2e_us_;
  __vec4_f y2_load79_2e_i_2e_us_;
  __vec4_f y3_load80_2e_i_2e_us_;
  __vec4_f y4_load81_2e_i_2e_us_;
  __vec4_f z1_load89_2e_i_2e_us_;
  __vec4_f z2_load90_2e_i_2e_us_;
  __vec4_f z3_load91_2e_i_2e_us_;
  __vec4_f z4_load92_2e_i_2e_us_;
  uint32_t add_i_load101_stride_load_2e_i_2e_us_;
  uint32_t j_2e_0_2e_i10_2e_us_;
  uint32_t j_2e_0_2e_i10_2e_us___PHI;
  uint32_t mul_j_load9_height_load10_2e_i_2e_us_;
  uint32_t add_mul__mul_width_load82_height_load83_offset_load84_2e_i_2e_us_;
  uint32_t add_mul__mul_width_load93_height_load94_offset_load95_2e_i_2e_us_;

  ;
  ;
  ;
  ;
  ;
  tmp__13_ = ((uint8_t *)(&x1_2e_i_));
  tmp__14_ = ((uint8_t *)(&y1_2e_i_));
  tmp__15_ = ((uint8_t *)(&z1_2e_i_));
  tmp__16_ = ((uint8_t *)(&x2_2e_i_));
  tmp__17_ = ((uint8_t *)(&y2_2e_i_));
  tmp__18_ = ((uint8_t *)(&z2_2e_i_));
  tmp__19_ = ((uint8_t *)(&x3_2e_i_));
  tmp__20_ = ((uint8_t *)(&y3_2e_i_));
  tmp__21_ = ((uint8_t *)(&z3_2e_i_));
  tmp__22_ = ((uint8_t *)(&x4_2e_i_));
  tmp__23_ = ((uint8_t *)(&y4_2e_i_));
  tmp__24_ = ((uint8_t *)(&z4_2e_i_));
  ;
  bitop_2e_i_ = width_ & 4294967292u;
  ;
  ;
  if ((((int32_t)height_) > ((int32_t)0u))) {
    goto for_loop_2e_i_2e_lr_2e_ph_label;
  } else {
    goto hwc2cwh____uniuniun_3C_unf_3E_un_3C_unf_3E_un_3C_unf_3E__2e_exit_label;
  }

for_loop_2e_i_2e_lr_2e_ph_label : {
  mul_width_load72_height_load73_2e_i_ =
      ((uint32_t)(((uint32_t)height_) * ((uint32_t)width_)));
  mul__mul_width_load93_height_load94_2e_i_ =
      mul_width_load72_height_load73_2e_i_ << 1u;
  if ((((int32_t)width_) > ((int32_t)0u))) {
    j_2e_0_2e_i10_2e_us___PHI = 0u; /* for PHI node */
    goto for_loop13_2e_i_2e_lr_2e_ph_2e_us_label;
  } else {
    goto hwc2cwh____uniuniun_3C_unf_3E_un_3C_unf_3E_un_3C_unf_3E__2e_exit_label;
  }
}
  do { /* Syntactic loop 'for_loop13.i.lr.ph.us' to make GCC happy */
  for_loop13_2e_i_2e_lr_2e_ph_2e_us_label : {
    j_2e_0_2e_i10_2e_us_ = j_2e_0_2e_i10_2e_us___PHI;
    mul_j_load9_height_load10_2e_i_2e_us_ =
        ((uint32_t)(((uint32_t)j_2e_0_2e_i10_2e_us_) * ((uint32_t)height_)));
    ;
    ;
    add_mul__mul_width_load82_height_load83_offset_load84_2e_i_2e_us_ =
        ((uint32_t)(((uint32_t)mul_j_load9_height_load10_2e_i_2e_us_) +
                    ((uint32_t)mul_width_load72_height_load73_2e_i_)));
    add_mul__mul_width_load93_height_load94_offset_load95_2e_i_2e_us_ =
        ((uint32_t)(((uint32_t)mul_j_load9_height_load10_2e_i_2e_us_) +
                    ((uint32_t)mul__mul_width_load93_height_load94_2e_i_)));
    i_2e_0_2e_i8_2e_us___PHI = 0u; /* for PHI node */
    goto for_loop13_2e_i_2e_us_label;
  }
    do { /* Syntactic loop 'for_loop13.i.us' to make GCC happy */
    for_loop13_2e_i_2e_us_label : {
      i_2e_0_2e_i8_2e_us_ = i_2e_0_2e_i8_2e_us___PHI;
      add_offset_load_i_load19_2e_i_2e_us_ =
          ((uint32_t)(((uint32_t)i_2e_0_2e_i8_2e_us_) +
                      ((uint32_t)mul_j_load9_height_load10_2e_i_2e_us_)));
      add_add_offset_load_i_load19__to_int64_2e_i_2e_us_ =
          ((int64_t)(int32_t)add_offset_load_i_load19_2e_i_2e_us_);
      ;
      ;
      ;
      ;
      __aos_to_soa3_float(
          ((&input_[(
              (int64_t)add_add_offset_load_i_load19__to_int64_2e_i_2e_us_)])),
          (&x1_2e_i_), (&y1_2e_i_), (&z1_2e_i_));
      ;
      ;
      ;
      ;
      __aos_to_soa3_float(((&input_[((int64_t)(((int64_t)(int32_t)(((uint32_t)(
                              ((uint32_t)add_offset_load_i_load19_2e_i_2e_us_) +
                              ((uint32_t)1u)))))))])),
                          (&x2_2e_i_), (&y2_2e_i_), (&z2_2e_i_));
      ;
      ;
      ;
      ;
      __aos_to_soa3_float(((&input_[((int64_t)(((int64_t)(int32_t)(((uint32_t)(
                              ((uint32_t)add_offset_load_i_load19_2e_i_2e_us_) +
                              ((uint32_t)2u)))))))])),
                          (&x3_2e_i_), (&y3_2e_i_), (&z3_2e_i_));
      ;
      ;
      ;
      ;
      __aos_to_soa3_float(((&input_[((int64_t)(((int64_t)(int32_t)(((uint32_t)(
                              ((uint32_t)add_offset_load_i_load19_2e_i_2e_us_) +
                              ((uint32_t)3u)))))))])),
                          (&x4_2e_i_), (&y4_2e_i_), (&z4_2e_i_));
      ;
      x1_load_2e_i_2e_us_ = __load<16>((&x1_2e_i_));
      ;
      ;
      x2_load_2e_i_2e_us_ = __load<16>((&x2_2e_i_));
      ;
      ;
      x3_load_2e_i_2e_us_ = __load<16>((&x3_2e_i_));
      ;
      ;
      x4_load_2e_i_2e_us_ = __load<16>((&x4_2e_i_));
      ;
      ;
      ;
      ;
      ;
      ;
      ;
      ;
      ;
      __soa_to_aos4_float(
          x1_load_2e_i_2e_us_, x2_load_2e_i_2e_us_, x3_load_2e_i_2e_us_,
          x4_load_2e_i_2e_us_,
          ((&result_[(
              (int64_t)add_add_offset_load_i_load19__to_int64_2e_i_2e_us_)])));
      y1_load78_2e_i_2e_us_ = __load<16>((&y1_2e_i_));
      ;
      y2_load79_2e_i_2e_us_ = __load<16>((&y2_2e_i_));
      ;
      y3_load80_2e_i_2e_us_ = __load<16>((&y3_2e_i_));
      ;
      y4_load81_2e_i_2e_us_ = __load<16>((&y4_2e_i_));
      ;
      ;
      __soa_to_aos4_float(
          y1_load78_2e_i_2e_us_, y2_load79_2e_i_2e_us_, y3_load80_2e_i_2e_us_,
          y4_load81_2e_i_2e_us_,
          ((&result_[((int64_t)(((int64_t)(int32_t)(((uint32_t)(
              ((uint32_t)
                   add_mul__mul_width_load82_height_load83_offset_load84_2e_i_2e_us_) +
              ((uint32_t)i_2e_0_2e_i8_2e_us_)))))))])));
      z1_load89_2e_i_2e_us_ = __load<16>((&z1_2e_i_));
      ;
      z2_load90_2e_i_2e_us_ = __load<16>((&z2_2e_i_));
      ;
      z3_load91_2e_i_2e_us_ = __load<16>((&z3_2e_i_));
      ;
      z4_load92_2e_i_2e_us_ = __load<16>((&z4_2e_i_));
      ;
      ;
      __soa_to_aos4_float(
          z1_load89_2e_i_2e_us_, z2_load90_2e_i_2e_us_, z3_load91_2e_i_2e_us_,
          z4_load92_2e_i_2e_us_,
          ((&result_[((int64_t)(((int64_t)(int32_t)(((uint32_t)(
              ((uint32_t)
                   add_mul__mul_width_load93_height_load94_offset_load95_2e_i_2e_us_) +
              ((uint32_t)i_2e_0_2e_i8_2e_us_)))))))])));
      add_i_load101_stride_load_2e_i_2e_us_ = ((uint32_t)(
          ((uint32_t)i_2e_0_2e_i8_2e_us_) + ((uint32_t)bitop_2e_i_)));
      ;
      if ((((int32_t)add_i_load101_stride_load_2e_i_2e_us_) <
           ((int32_t)width_))) {
        i_2e_0_2e_i8_2e_us___PHI =
            add_i_load101_stride_load_2e_i_2e_us_; /* for PHI node */
        goto for_loop13_2e_i_2e_us_label;
      } else {
        goto for_exit14_2e_i_2e_us_label;
      }
    }
    } while (1); /* end of syntactic loop 'for_loop13.i.us' */
  for_exit14_2e_i_2e_us_label : {
    j_load102_plus1_2e_i_2e_us_ =
        ((uint32_t)(((uint32_t)j_2e_0_2e_i10_2e_us_) + ((uint32_t)1u)));
    ;
    if ((j_load102_plus1_2e_i_2e_us_ == height_)) {
      goto hwc2cwh____uniuniun_3C_unf_3E_un_3C_unf_3E_un_3C_unf_3E__2e_exit_label;
    } else {
      j_2e_0_2e_i10_2e_us___PHI =
          j_load102_plus1_2e_i_2e_us_; /* for PHI node */
      goto for_loop13_2e_i_2e_lr_2e_ph_2e_us_label;
    }
  }
  } while (1); /* end of syntactic loop 'for_loop13.i.lr.ph.us' */
hwc2cwh____uniuniun_3C_unf_3E_un_3C_unf_3E_un_3C_unf_3E__2e_exit_label : {
  return;
}
}

void hwc2cwh(uint32_t width_, uint32_t height_, float *mean_, float *input_,
             float *result_) {
  __vec4_f x1_2e_i_; /* Address-exposed local */
  __vec4_f y1_2e_i_; /* Address-exposed local */
  __vec4_f z1_2e_i_; /* Address-exposed local */
  __vec4_f x2_2e_i_; /* Address-exposed local */
  __vec4_f y2_2e_i_; /* Address-exposed local */
  __vec4_f z2_2e_i_; /* Address-exposed local */
  __vec4_f x3_2e_i_; /* Address-exposed local */
  __vec4_f y3_2e_i_; /* Address-exposed local */
  __vec4_f z3_2e_i_; /* Address-exposed local */
  __vec4_f x4_2e_i_; /* Address-exposed local */
  __vec4_f y4_2e_i_; /* Address-exposed local */
  __vec4_f z4_2e_i_; /* Address-exposed local */
  uint8_t *tmp__25_;
  uint8_t *tmp__26_;
  uint8_t *tmp__27_;
  uint8_t *tmp__28_;
  uint8_t *tmp__29_;
  uint8_t *tmp__30_;
  uint8_t *tmp__31_;
  uint8_t *tmp__32_;
  uint8_t *tmp__33_;
  uint8_t *tmp__34_;
  uint8_t *tmp__35_;
  uint8_t *tmp__36_;
  uint32_t bitop_2e_i_;
  uint32_t mul_width_load72_height_load73_2e_i_;
  uint32_t mul__mul_width_load93_height_load94_2e_i_;
  uint32_t j_load102_plus1_2e_i_2e_us_;
  uint32_t i_2e_0_2e_i9_2e_us_;
  uint32_t i_2e_0_2e_i9_2e_us___PHI;
  uint32_t add_offset_load_i_load19_2e_i_2e_us_;
  uint64_t add_add_offset_load_i_load19__to_int64_2e_i_2e_us_;
  __vec4_f x1_load_2e_i_2e_us_;
  __vec4_f x2_load_2e_i_2e_us_;
  __vec4_f x3_load_2e_i_2e_us_;
  __vec4_f x4_load_2e_i_2e_us_;
  __vec4_f y1_load78_2e_i_2e_us_;
  __vec4_f y2_load79_2e_i_2e_us_;
  __vec4_f y3_load80_2e_i_2e_us_;
  __vec4_f y4_load81_2e_i_2e_us_;
  __vec4_f z1_load89_2e_i_2e_us_;
  __vec4_f z2_load90_2e_i_2e_us_;
  __vec4_f z3_load91_2e_i_2e_us_;
  __vec4_f z4_load92_2e_i_2e_us_;
  uint32_t add_i_load101_stride_load_2e_i_2e_us_;
  uint32_t j_2e_0_2e_i11_2e_us_;
  uint32_t j_2e_0_2e_i11_2e_us___PHI;
  uint32_t mul_j_load9_height_load10_2e_i_2e_us_;
  float mean_load_offset_load_2e_i_2e_us_;
  __vec4_f mean_load_offset_load_2e_i_2e_us_smear_;
  uint32_t add_mul__mul_width_load82_height_load83_offset_load84_2e_i_2e_us_;
  uint32_t add_mul__mul_width_load93_height_load94_offset_load95_2e_i_2e_us_;

  ;
  ;
  ;
  ;
  ;
  ;
  tmp__25_ = ((uint8_t *)(&x1_2e_i_));
  tmp__26_ = ((uint8_t *)(&y1_2e_i_));
  tmp__27_ = ((uint8_t *)(&z1_2e_i_));
  tmp__28_ = ((uint8_t *)(&x2_2e_i_));
  tmp__29_ = ((uint8_t *)(&y2_2e_i_));
  tmp__30_ = ((uint8_t *)(&z2_2e_i_));
  tmp__31_ = ((uint8_t *)(&x3_2e_i_));
  tmp__32_ = ((uint8_t *)(&y3_2e_i_));
  tmp__33_ = ((uint8_t *)(&z3_2e_i_));
  tmp__34_ = ((uint8_t *)(&x4_2e_i_));
  tmp__35_ = ((uint8_t *)(&y4_2e_i_));
  tmp__36_ = ((uint8_t *)(&z4_2e_i_));
  ;
  bitop_2e_i_ = width_ & 4294967292u;
  ;
  ;
  if ((((int32_t)height_) > ((int32_t)0u))) {
    goto for_loop_2e_i_2e_lr_2e_ph_label;
  } else {
    goto hwc2cwh____uniuniun_3C_unf_3E_un_3C_unf_3E_un_3C_unf_3E__2e_exit_label;
  }

for_loop_2e_i_2e_lr_2e_ph_label : {
  mul_width_load72_height_load73_2e_i_ =
      ((uint32_t)(((uint32_t)height_) * ((uint32_t)width_)));
  mul__mul_width_load93_height_load94_2e_i_ =
      mul_width_load72_height_load73_2e_i_ << 1u;
  if ((((int32_t)width_) > ((int32_t)0u))) {
    j_2e_0_2e_i11_2e_us___PHI = 0u; /* for PHI node */
    goto for_loop13_2e_i_2e_lr_2e_ph_2e_us_label;
  } else {
    goto hwc2cwh____uniuniun_3C_unf_3E_un_3C_unf_3E_un_3C_unf_3E__2e_exit_label;
  }
}
  do { /* Syntactic loop 'for_loop13.i.lr.ph.us' to make GCC happy */
  for_loop13_2e_i_2e_lr_2e_ph_2e_us_label : {
    j_2e_0_2e_i11_2e_us_ = j_2e_0_2e_i11_2e_us___PHI;
    mul_j_load9_height_load10_2e_i_2e_us_ =
        ((uint32_t)(((uint32_t)j_2e_0_2e_i11_2e_us_) * ((uint32_t)height_)));
    ;
    ;
    mean_load_offset_load_2e_i_2e_us_ = *mean_;
    mean_load_offset_load_2e_i_2e_us_smear_ =
        __smear_float<__vec4_f>(mean_load_offset_load_2e_i_2e_us_);
    add_mul__mul_width_load82_height_load83_offset_load84_2e_i_2e_us_ =
        ((uint32_t)(((uint32_t)mul_j_load9_height_load10_2e_i_2e_us_) +
                    ((uint32_t)mul_width_load72_height_load73_2e_i_)));
    add_mul__mul_width_load93_height_load94_offset_load95_2e_i_2e_us_ =
        ((uint32_t)(((uint32_t)mul_j_load9_height_load10_2e_i_2e_us_) +
                    ((uint32_t)mul__mul_width_load93_height_load94_2e_i_)));
    i_2e_0_2e_i9_2e_us___PHI = 0u; /* for PHI node */
    goto for_loop13_2e_i_2e_us_label;
  }
    do { /* Syntactic loop 'for_loop13.i.us' to make GCC happy */
    for_loop13_2e_i_2e_us_label : {
      i_2e_0_2e_i9_2e_us_ = i_2e_0_2e_i9_2e_us___PHI;
      add_offset_load_i_load19_2e_i_2e_us_ =
          ((uint32_t)(((uint32_t)i_2e_0_2e_i9_2e_us_) +
                      ((uint32_t)mul_j_load9_height_load10_2e_i_2e_us_)));
      add_add_offset_load_i_load19__to_int64_2e_i_2e_us_ =
          ((int64_t)(int32_t)add_offset_load_i_load19_2e_i_2e_us_);
      ;
      ;
      ;
      ;
      __aos_to_soa3_float(
          ((&input_[(
              (int64_t)add_add_offset_load_i_load19__to_int64_2e_i_2e_us_)])),
          (&x1_2e_i_), (&y1_2e_i_), (&z1_2e_i_));
      ;
      ;
      ;
      ;
      __aos_to_soa3_float(((&input_[((int64_t)(((int64_t)(int32_t)(((uint32_t)(
                              ((uint32_t)add_offset_load_i_load19_2e_i_2e_us_) +
                              ((uint32_t)1u)))))))])),
                          (&x2_2e_i_), (&y2_2e_i_), (&z2_2e_i_));
      ;
      ;
      ;
      ;
      __aos_to_soa3_float(((&input_[((int64_t)(((int64_t)(int32_t)(((uint32_t)(
                              ((uint32_t)add_offset_load_i_load19_2e_i_2e_us_) +
                              ((uint32_t)2u)))))))])),
                          (&x3_2e_i_), (&y3_2e_i_), (&z3_2e_i_));
      ;
      ;
      ;
      ;
      __aos_to_soa3_float(((&input_[((int64_t)(((int64_t)(int32_t)(((uint32_t)(
                              ((uint32_t)add_offset_load_i_load19_2e_i_2e_us_) +
                              ((uint32_t)3u)))))))])),
                          (&x4_2e_i_), (&y4_2e_i_), (&z4_2e_i_));
      ;
      x1_load_2e_i_2e_us_ = __load<16>((&x1_2e_i_));
      ;
      ;
      x2_load_2e_i_2e_us_ = __load<16>((&x2_2e_i_));
      ;
      ;
      x3_load_2e_i_2e_us_ = __load<16>((&x3_2e_i_));
      ;
      ;
      x4_load_2e_i_2e_us_ = __load<16>((&x4_2e_i_));
      ;
      ;
      ;
      ;
      ;
      ;
      ;
      ;
      ;
      __soa_to_aos4_float(
          (__sub(x1_load_2e_i_2e_us_, mean_load_offset_load_2e_i_2e_us_smear_)),
          (__sub(x2_load_2e_i_2e_us_, mean_load_offset_load_2e_i_2e_us_smear_)),
          (__sub(x3_load_2e_i_2e_us_, mean_load_offset_load_2e_i_2e_us_smear_)),
          (__sub(x4_load_2e_i_2e_us_, mean_load_offset_load_2e_i_2e_us_smear_)),
          ((&result_[(
              (int64_t)add_add_offset_load_i_load19__to_int64_2e_i_2e_us_)])));
      y1_load78_2e_i_2e_us_ = __load<16>((&y1_2e_i_));
      ;
      y2_load79_2e_i_2e_us_ = __load<16>((&y2_2e_i_));
      ;
      y3_load80_2e_i_2e_us_ = __load<16>((&y3_2e_i_));
      ;
      y4_load81_2e_i_2e_us_ = __load<16>((&y4_2e_i_));
      ;
      ;
      __soa_to_aos4_float(
          y1_load78_2e_i_2e_us_, y2_load79_2e_i_2e_us_, y3_load80_2e_i_2e_us_,
          y4_load81_2e_i_2e_us_,
          ((&result_[((int64_t)(((int64_t)(int32_t)(((uint32_t)(
              ((uint32_t)
                   add_mul__mul_width_load82_height_load83_offset_load84_2e_i_2e_us_) +
              ((uint32_t)i_2e_0_2e_i9_2e_us_)))))))])));
      z1_load89_2e_i_2e_us_ = __load<16>((&z1_2e_i_));
      ;
      z2_load90_2e_i_2e_us_ = __load<16>((&z2_2e_i_));
      ;
      z3_load91_2e_i_2e_us_ = __load<16>((&z3_2e_i_));
      ;
      z4_load92_2e_i_2e_us_ = __load<16>((&z4_2e_i_));
      ;
      ;
      __soa_to_aos4_float(
          z1_load89_2e_i_2e_us_, z2_load90_2e_i_2e_us_, z3_load91_2e_i_2e_us_,
          z4_load92_2e_i_2e_us_,
          ((&result_[((int64_t)(((int64_t)(int32_t)(((uint32_t)(
              ((uint32_t)
                   add_mul__mul_width_load93_height_load94_offset_load95_2e_i_2e_us_) +
              ((uint32_t)i_2e_0_2e_i9_2e_us_)))))))])));
      add_i_load101_stride_load_2e_i_2e_us_ = ((uint32_t)(
          ((uint32_t)i_2e_0_2e_i9_2e_us_) + ((uint32_t)bitop_2e_i_)));
      ;
      if ((((int32_t)add_i_load101_stride_load_2e_i_2e_us_) <
           ((int32_t)width_))) {
        i_2e_0_2e_i9_2e_us___PHI =
            add_i_load101_stride_load_2e_i_2e_us_; /* for PHI node */
        goto for_loop13_2e_i_2e_us_label;
      } else {
        goto for_exit14_2e_i_2e_us_label;
      }
    }
    } while (1); /* end of syntactic loop 'for_loop13.i.us' */
  for_exit14_2e_i_2e_us_label : {
    j_load102_plus1_2e_i_2e_us_ =
        ((uint32_t)(((uint32_t)j_2e_0_2e_i11_2e_us_) + ((uint32_t)1u)));
    ;
    if ((j_load102_plus1_2e_i_2e_us_ == height_)) {
      goto hwc2cwh____uniuniun_3C_unf_3E_un_3C_unf_3E_un_3C_unf_3E__2e_exit_label;
    } else {
      j_2e_0_2e_i11_2e_us___PHI =
          j_load102_plus1_2e_i_2e_us_; /* for PHI node */
      goto for_loop13_2e_i_2e_lr_2e_ph_2e_us_label;
    }
  }
  } while (1); /* end of syntactic loop 'for_loop13.i.lr.ph.us' */
hwc2cwh____uniuniun_3C_unf_3E_un_3C_unf_3E_un_3C_unf_3E__2e_exit_label : {
  return;
}
}

void hwc2cwh2(uint32_t width_, uint32_t height_, float *input_,
              float *result_) {
  __vec4_f x1_2e_i_; /* Address-exposed local */
  __vec4_f y1_2e_i_; /* Address-exposed local */
  __vec4_f z1_2e_i_; /* Address-exposed local */
  __vec4_f x2_2e_i_; /* Address-exposed local */
  __vec4_f y2_2e_i_; /* Address-exposed local */
  __vec4_f z2_2e_i_; /* Address-exposed local */
  __vec4_f x3_2e_i_; /* Address-exposed local */
  __vec4_f y3_2e_i_; /* Address-exposed local */
  __vec4_f z3_2e_i_; /* Address-exposed local */
  __vec4_f x4_2e_i_; /* Address-exposed local */
  __vec4_f y4_2e_i_; /* Address-exposed local */
  __vec4_f z4_2e_i_; /* Address-exposed local */
  uint8_t *tmp__37_;
  uint8_t *tmp__38_;
  uint8_t *tmp__39_;
  uint8_t *tmp__40_;
  uint8_t *tmp__41_;
  uint8_t *tmp__42_;
  uint8_t *tmp__43_;
  uint8_t *tmp__44_;
  uint8_t *tmp__45_;
  uint8_t *tmp__46_;
  uint8_t *tmp__47_;
  uint8_t *tmp__48_;
  uint32_t bitop_2e_i_;
  uint32_t mul_width_load72_height_load73_2e_i_;
  uint32_t mul__mul_width_load93_height_load94_2e_i_;
  uint32_t j_load102_plus1_2e_i_2e_us_;
  uint32_t i_2e_0_2e_i8_2e_us_;
  uint32_t i_2e_0_2e_i8_2e_us___PHI;
  uint32_t add_offset_load_i_load19_2e_i_2e_us_;
  uint64_t add_add_offset_load_i_load19__to_int64_2e_i_2e_us_;
  __vec4_f x1_load_2e_i_2e_us_;
  __vec4_f x2_load_2e_i_2e_us_;
  __vec4_f x3_load_2e_i_2e_us_;
  __vec4_f x4_load_2e_i_2e_us_;
  __vec4_f y1_load78_2e_i_2e_us_;
  __vec4_f y2_load79_2e_i_2e_us_;
  __vec4_f y3_load80_2e_i_2e_us_;
  __vec4_f y4_load81_2e_i_2e_us_;
  __vec4_f z1_load89_2e_i_2e_us_;
  __vec4_f z2_load90_2e_i_2e_us_;
  __vec4_f z3_load91_2e_i_2e_us_;
  __vec4_f z4_load92_2e_i_2e_us_;
  uint32_t add_i_load101_stride_load_2e_i_2e_us_;
  uint32_t j_2e_0_2e_i10_2e_us_;
  uint32_t j_2e_0_2e_i10_2e_us___PHI;
  uint32_t mul_j_load9_height_load10_2e_i_2e_us_;
  uint32_t add_mul__mul_width_load82_height_load83_offset_load84_2e_i_2e_us_;
  uint32_t add_mul__mul_width_load93_height_load94_offset_load95_2e_i_2e_us_;

  ;
  ;
  ;
  ;
  ;
  tmp__37_ = ((uint8_t *)(&x1_2e_i_));
  tmp__38_ = ((uint8_t *)(&y1_2e_i_));
  tmp__39_ = ((uint8_t *)(&z1_2e_i_));
  tmp__40_ = ((uint8_t *)(&x2_2e_i_));
  tmp__41_ = ((uint8_t *)(&y2_2e_i_));
  tmp__42_ = ((uint8_t *)(&z2_2e_i_));
  tmp__43_ = ((uint8_t *)(&x3_2e_i_));
  tmp__44_ = ((uint8_t *)(&y3_2e_i_));
  tmp__45_ = ((uint8_t *)(&z3_2e_i_));
  tmp__46_ = ((uint8_t *)(&x4_2e_i_));
  tmp__47_ = ((uint8_t *)(&y4_2e_i_));
  tmp__48_ = ((uint8_t *)(&z4_2e_i_));
  ;
  bitop_2e_i_ = width_ & 4294967292u;
  ;
  ;
  if ((((int32_t)height_) > ((int32_t)0u))) {
    goto for_loop_2e_i_2e_lr_2e_ph_label;
  } else {
    goto hwc2cwh____uniuniun_3C_unf_3E_un_3C_unf_3E_un_3C_unf_3E__2e_exit_label;
  }

for_loop_2e_i_2e_lr_2e_ph_label : {
  mul_width_load72_height_load73_2e_i_ =
      ((uint32_t)(((uint32_t)height_) * ((uint32_t)width_)));
  mul__mul_width_load93_height_load94_2e_i_ =
      mul_width_load72_height_load73_2e_i_ << 1u;
  if ((((int32_t)width_) > ((int32_t)0u))) {
    j_2e_0_2e_i10_2e_us___PHI = 0u; /* for PHI node */
    goto for_loop13_2e_i_2e_lr_2e_ph_2e_us_label;
  } else {
    goto hwc2cwh____uniuniun_3C_unf_3E_un_3C_unf_3E_un_3C_unf_3E__2e_exit_label;
  }
}
  do { /* Syntactic loop 'for_loop13.i.lr.ph.us' to make GCC happy */
  for_loop13_2e_i_2e_lr_2e_ph_2e_us_label : {
    j_2e_0_2e_i10_2e_us_ = j_2e_0_2e_i10_2e_us___PHI;
    mul_j_load9_height_load10_2e_i_2e_us_ =
        ((uint32_t)(((uint32_t)j_2e_0_2e_i10_2e_us_) * ((uint32_t)height_)));
    ;
    ;
    add_mul__mul_width_load82_height_load83_offset_load84_2e_i_2e_us_ =
        ((uint32_t)(((uint32_t)mul_j_load9_height_load10_2e_i_2e_us_) +
                    ((uint32_t)mul_width_load72_height_load73_2e_i_)));
    add_mul__mul_width_load93_height_load94_offset_load95_2e_i_2e_us_ =
        ((uint32_t)(((uint32_t)mul_j_load9_height_load10_2e_i_2e_us_) +
                    ((uint32_t)mul__mul_width_load93_height_load94_2e_i_)));
    i_2e_0_2e_i8_2e_us___PHI = 0u; /* for PHI node */
    goto for_loop13_2e_i_2e_us_label;
  }
    do { /* Syntactic loop 'for_loop13.i.us' to make GCC happy */
    for_loop13_2e_i_2e_us_label : {
      i_2e_0_2e_i8_2e_us_ = i_2e_0_2e_i8_2e_us___PHI;
      add_offset_load_i_load19_2e_i_2e_us_ =
          ((uint32_t)(((uint32_t)i_2e_0_2e_i8_2e_us_) +
                      ((uint32_t)mul_j_load9_height_load10_2e_i_2e_us_)));
      add_add_offset_load_i_load19__to_int64_2e_i_2e_us_ =
          ((int64_t)(int32_t)add_offset_load_i_load19_2e_i_2e_us_);
      ;
      ;
      ;
      ;
      __aos_to_soa3_float(
          ((&input_[(
              (int64_t)add_add_offset_load_i_load19__to_int64_2e_i_2e_us_)])),
          (&x1_2e_i_), (&y1_2e_i_), (&z1_2e_i_));
      ;
      ;
      ;
      ;
      __aos_to_soa3_float(((&input_[((int64_t)(((int64_t)(int32_t)(((uint32_t)(
                              ((uint32_t)add_offset_load_i_load19_2e_i_2e_us_) +
                              ((uint32_t)1u)))))))])),
                          (&x2_2e_i_), (&y2_2e_i_), (&z2_2e_i_));
      ;
      ;
      ;
      ;
      __aos_to_soa3_float(((&input_[((int64_t)(((int64_t)(int32_t)(((uint32_t)(
                              ((uint32_t)add_offset_load_i_load19_2e_i_2e_us_) +
                              ((uint32_t)2u)))))))])),
                          (&x3_2e_i_), (&y3_2e_i_), (&z3_2e_i_));
      ;
      ;
      ;
      ;
      __aos_to_soa3_float(((&input_[((int64_t)(((int64_t)(int32_t)(((uint32_t)(
                              ((uint32_t)add_offset_load_i_load19_2e_i_2e_us_) +
                              ((uint32_t)3u)))))))])),
                          (&x4_2e_i_), (&y4_2e_i_), (&z4_2e_i_));
      ;
      x1_load_2e_i_2e_us_ = __load<16>((&x1_2e_i_));
      ;
      ;
      x2_load_2e_i_2e_us_ = __load<16>((&x2_2e_i_));
      ;
      ;
      x3_load_2e_i_2e_us_ = __load<16>((&x3_2e_i_));
      ;
      ;
      x4_load_2e_i_2e_us_ = __load<16>((&x4_2e_i_));
      ;
      ;
      ;
      ;
      ;
      ;
      ;
      ;
      ;
      __soa_to_aos4_float(
          x1_load_2e_i_2e_us_, x2_load_2e_i_2e_us_, x3_load_2e_i_2e_us_,
          x4_load_2e_i_2e_us_,
          ((&result_[(
              (int64_t)add_add_offset_load_i_load19__to_int64_2e_i_2e_us_)])));
      y1_load78_2e_i_2e_us_ = __load<16>((&y1_2e_i_));
      ;
      y2_load79_2e_i_2e_us_ = __load<16>((&y2_2e_i_));
      ;
      y3_load80_2e_i_2e_us_ = __load<16>((&y3_2e_i_));
      ;
      y4_load81_2e_i_2e_us_ = __load<16>((&y4_2e_i_));
      ;
      ;
      __soa_to_aos4_float(
          y1_load78_2e_i_2e_us_, y2_load79_2e_i_2e_us_, y3_load80_2e_i_2e_us_,
          y4_load81_2e_i_2e_us_,
          ((&result_[((int64_t)(((int64_t)(int32_t)(((uint32_t)(
              ((uint32_t)
                   add_mul__mul_width_load82_height_load83_offset_load84_2e_i_2e_us_) +
              ((uint32_t)i_2e_0_2e_i8_2e_us_)))))))])));
      z1_load89_2e_i_2e_us_ = __load<16>((&z1_2e_i_));
      ;
      z2_load90_2e_i_2e_us_ = __load<16>((&z2_2e_i_));
      ;
      z3_load91_2e_i_2e_us_ = __load<16>((&z3_2e_i_));
      ;
      z4_load92_2e_i_2e_us_ = __load<16>((&z4_2e_i_));
      ;
      ;
      __soa_to_aos4_float(
          z1_load89_2e_i_2e_us_, z2_load90_2e_i_2e_us_, z3_load91_2e_i_2e_us_,
          z4_load92_2e_i_2e_us_,
          ((&result_[((int64_t)(((int64_t)(int32_t)(((uint32_t)(
              ((uint32_t)
                   add_mul__mul_width_load93_height_load94_offset_load95_2e_i_2e_us_) +
              ((uint32_t)i_2e_0_2e_i8_2e_us_)))))))])));
      add_i_load101_stride_load_2e_i_2e_us_ = ((uint32_t)(
          ((uint32_t)i_2e_0_2e_i8_2e_us_) + ((uint32_t)bitop_2e_i_)));
      ;
      if ((((int32_t)add_i_load101_stride_load_2e_i_2e_us_) <
           ((int32_t)width_))) {
        i_2e_0_2e_i8_2e_us___PHI =
            add_i_load101_stride_load_2e_i_2e_us_; /* for PHI node */
        goto for_loop13_2e_i_2e_us_label;
      } else {
        goto for_exit14_2e_i_2e_us_label;
      }
    }
    } while (1); /* end of syntactic loop 'for_loop13.i.us' */
  for_exit14_2e_i_2e_us_label : {
    j_load102_plus1_2e_i_2e_us_ =
        ((uint32_t)(((uint32_t)j_2e_0_2e_i10_2e_us_) + ((uint32_t)1u)));
    ;
    if ((j_load102_plus1_2e_i_2e_us_ == height_)) {
      goto hwc2cwh____uniuniun_3C_unf_3E_un_3C_unf_3E_un_3C_unf_3E__2e_exit_label;
    } else {
      j_2e_0_2e_i10_2e_us___PHI =
          j_load102_plus1_2e_i_2e_us_; /* for PHI node */
      goto for_loop13_2e_i_2e_lr_2e_ph_2e_us_label;
    }
  }
  } while (1); /* end of syntactic loop 'for_loop13.i.lr.ph.us' */
hwc2cwh____uniuniun_3C_unf_3E_un_3C_unf_3E_un_3C_unf_3E__2e_exit_label : {
  return;
}
}
